# Generated by Django 5.2.6 on 2025-10-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_referral_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='source_known',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
