# Generated by Django 5.2.6 on 2025-11-11 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_profile_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyXP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('pomodoro_xp', models.IntegerField(default=0)),
                ('markdown_xp', models.IntegerField(default=0)),
                ('vaultless_xp', models.IntegerField(default=0)),
                ('circular_xp', models.IntegerField(default=0)),
                ('soul_xp', models.IntegerField(default=0)),
                ('combo_xp', models.IntegerField(default=0)),
                ('tool_xp_capped', models.IntegerField(default=0)),
                ('streak_xp', models.IntegerField(default=0)),
                ('milestone_xp', models.IntegerField(default=0)),
                ('final_total_xp', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_xp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'day'], name='app_dailyxp_user_id_259101_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'day'), name='uq_dailyxp_user_day')],
            },
        ),
        migrations.CreateModel(
            name='MarkdownChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_day', models.DateField(db_index=True)),
                ('chunk_hash', models.CharField(db_index=True, max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markdown_chunks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'local_day', 'chunk_hash'), name='uq_md_chunk_once_per_day')],
            },
        ),
        migrations.CreateModel(
            name='MilestoneHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('streak_len', models.PositiveIntegerField()),
                ('xp_awarded', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'streak_len'], name='app_milesto_user_id_d1bf03_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'streak_len'), name='uq_milestone_once')],
            },
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.PositiveIntegerField(default=0)),
                ('longest', models.PositiveIntegerField(default=0)),
                ('last_qualified_day', models.DateField(blank=True, null=True)),
                ('timezone_name', models.CharField(default='Asia/Kolkata', max_length=64)),
                ('last_streak_save_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='app_streak_user_id_780bb7_idx')],
            },
        ),
        migrations.CreateModel(
            name='VaultlessDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_day', models.DateField(db_index=True)),
                ('fingerprint', models.CharField(db_index=True, max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaultless_domains', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'local_day', 'fingerprint'), name='uq_vaultless_domain_day_once')],
            },
        ),
        migrations.CreateModel(
            name='XPEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('local_day', models.DateField(db_index=True)),
                ('tool', models.CharField(blank=True, choices=[('pomodoro', 'Pomodoro'), ('markdown', 'Markdown'), ('vaultless', 'Vaultless'), ('circular', 'Circular'), ('soul', 'Soul')], max_length=16, null=True)),
                ('kind', models.CharField(choices=[('tool_xp', 'Tool XP'), ('combo_xp', 'Combo XP'), ('streak_xp', 'Streak XP'), ('milestone_xp', 'Milestone XP')], max_length=16)),
                ('points', models.IntegerField(default=0)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'local_day'], name='app_xpevent_user_id_23d06a_idx'), models.Index(fields=['user', 'tool', 'local_day'], name='app_xpevent_user_id_ffe1ec_idx')],
            },
        ),
    ]
